repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=800 ]
  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.3'
      hooks:
        -   id: poetry-check
        -   id: poetry-lock
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check
        language: system
        types_or: [ python, pyi ]
        args: [ --fix, --force-exclude ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"
      - id: run-tests
        name: Run pytest
        entry: pytest
        language: python
        types: [ python ]
